# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Cell.proto

from __future__ import absolute_import, print_function

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Cell.proto',
  package='pb',
  serialized_pb=_b('\n\nCell.proto\x12\x02pb\"\x87\x01\n\x04\x43\x65ll\x12\x0b\n\x03row\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66\x61mily\x18\x02 \x01(\x0c\x12\x11\n\tqualifier\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x1f\n\tcell_type\x18\x05 \x01(\x0e\x32\x0c.pb.CellType\x12\r\n\x05value\x18\x06 \x01(\x0c\x12\x0c\n\x04tags\x18\x07 \x01(\x0c\"\x8a\x01\n\x08KeyValue\x12\x0b\n\x03row\x18\x01 \x02(\x0c\x12\x0e\n\x06\x66\x61mily\x18\x02 \x02(\x0c\x12\x11\n\tqualifier\x18\x03 \x02(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x1e\n\x08key_type\x18\x05 \x01(\x0e\x32\x0c.pb.CellType\x12\r\n\x05value\x18\x06 \x01(\x0c\x12\x0c\n\x04tags\x18\x07 \x01(\x0c*`\n\x08\x43\x65llType\x12\x0b\n\x07MINIMUM\x10\x00\x12\x07\n\x03PUT\x10\x04\x12\n\n\x06\x44\x45LETE\x10\x08\x12\x11\n\rDELETE_COLUMN\x10\x0c\x12\x11\n\rDELETE_FAMILY\x10\x0e\x12\x0c\n\x07MAXIMUM\x10\xff\x01\x42=\n*org.apache.hadoop.hbase.protobuf.generatedB\nCellProtosH\x01\xa0\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CELLTYPE = _descriptor.EnumDescriptor(
  name='CellType',
  full_name='pb.CellType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MINIMUM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT', index=1, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_COLUMN', index=3, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_FAMILY', index=4, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXIMUM', index=5, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=297,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_CELLTYPE)

CellType = enum_type_wrapper.EnumTypeWrapper(_CELLTYPE)
MINIMUM = 0
PUT = 4
DELETE = 8
DELETE_COLUMN = 12
DELETE_FAMILY = 14
MAXIMUM = 255



_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='pb.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='pb.Cell.row', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='family', full_name='pb.Cell.family', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qualifier', full_name='pb.Cell.qualifier', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pb.Cell.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_type', full_name='pb.Cell.cell_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.Cell.value', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='pb.Cell.tags', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=154,
)


_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='pb.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='pb.KeyValue.row', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='family', full_name='pb.KeyValue.family', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qualifier', full_name='pb.KeyValue.qualifier', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pb.KeyValue.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key_type', full_name='pb.KeyValue.key_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.KeyValue.value', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='pb.KeyValue.tags', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=295,
)

_CELL.fields_by_name['cell_type'].enum_type = _CELLTYPE
_KEYVALUE.fields_by_name['key_type'].enum_type = _CELLTYPE
DESCRIPTOR.message_types_by_name['Cell'] = _CELL
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.enum_types_by_name['CellType'] = _CELLTYPE

Cell = _reflection.GeneratedProtocolMessageType('Cell', (_message.Message,), dict(
  DESCRIPTOR = _CELL,
  __module__ = 'Cell_pb2'
  # @@protoc_insertion_point(class_scope:pb.Cell)
  ))
_sym_db.RegisterMessage(Cell)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUE,
  __module__ = 'Cell_pb2'
  # @@protoc_insertion_point(class_scope:pb.KeyValue)
  ))
_sym_db.RegisterMessage(KeyValue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\nCellProtosH\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
