# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RPC.proto

from __future__ import absolute_import, print_function

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

from . import HBase_pb2
from . import Tracing_pb2

_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RPC.proto',
  package='pb',
  serialized_pb=_b('\n\tRPC.proto\x12\x02pb\x1a\rTracing.proto\x1a\x0bHBase.proto\"<\n\x0fUserInformation\x12\x16\n\x0e\x65\x66\x66\x65\x63tive_user\x18\x01 \x02(\t\x12\x11\n\treal_user\x18\x02 \x01(\t\"o\n\x0bVersionInfo\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\x0b\n\x03url\x18\x02 \x02(\t\x12\x10\n\x08revision\x18\x03 \x02(\t\x12\x0c\n\x04user\x18\x04 \x02(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x02(\t\x12\x14\n\x0csrc_checksum\x18\x06 \x02(\t\"\xbc\x01\n\x10\x43onnectionHeader\x12&\n\tuser_info\x18\x01 \x01(\x0b\x32\x13.pb.UserInformation\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x1e\n\x16\x63\x65ll_block_codec_class\x18\x03 \x01(\t\x12#\n\x1b\x63\x65ll_block_compressor_class\x18\x04 \x01(\t\x12%\n\x0cversion_info\x18\x05 \x01(\x0b\x32\x0f.pb.VersionInfo\"\x1f\n\rCellBlockMeta\x12\x0e\n\x06length\x18\x01 \x01(\r\"|\n\x11\x45xceptionResponse\x12\x1c\n\x14\x65xception_class_name\x18\x01 \x01(\t\x12\x13\n\x0bstack_trace\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x14\n\x0c\x64o_not_retry\x18\x05 \x01(\x08\"\xac\x01\n\rRequestHeader\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\r\x12 \n\ntrace_info\x18\x02 \x01(\x0b\x32\x0c.pb.RPCTInfo\x12\x13\n\x0bmethod_name\x18\x03 \x01(\t\x12\x15\n\rrequest_param\x18\x04 \x01(\x08\x12*\n\x0f\x63\x65ll_block_meta\x18\x05 \x01(\x0b\x32\x11.pb.CellBlockMeta\x12\x10\n\x08priority\x18\x06 \x01(\r\"w\n\x0eResponseHeader\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\r\x12(\n\texception\x18\x02 \x01(\x0b\x32\x15.pb.ExceptionResponse\x12*\n\x0f\x63\x65ll_block_meta\x18\x03 \x01(\x0b\x32\x11.pb.CellBlockMetaB<\n*org.apache.hadoop.hbase.protobuf.generatedB\tRPCProtosH\x01\xa0\x01\x01')
  ,
  dependencies=[Tracing_pb2.DESCRIPTOR,HBase_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERINFORMATION = _descriptor.Descriptor(
  name='UserInformation',
  full_name='pb.UserInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='effective_user', full_name='pb.UserInformation.effective_user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real_user', full_name='pb.UserInformation.real_user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=105,
)


_VERSIONINFO = _descriptor.Descriptor(
  name='VersionInfo',
  full_name='pb.VersionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='pb.VersionInfo.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='pb.VersionInfo.url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='revision', full_name='pb.VersionInfo.revision', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='pb.VersionInfo.user', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='pb.VersionInfo.date', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_checksum', full_name='pb.VersionInfo.src_checksum', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=218,
)


_CONNECTIONHEADER = _descriptor.Descriptor(
  name='ConnectionHeader',
  full_name='pb.ConnectionHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_info', full_name='pb.ConnectionHeader.user_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='pb.ConnectionHeader.service_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_block_codec_class', full_name='pb.ConnectionHeader.cell_block_codec_class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_block_compressor_class', full_name='pb.ConnectionHeader.cell_block_compressor_class', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version_info', full_name='pb.ConnectionHeader.version_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=409,
)


_CELLBLOCKMETA = _descriptor.Descriptor(
  name='CellBlockMeta',
  full_name='pb.CellBlockMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='pb.CellBlockMeta.length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=442,
)


_EXCEPTIONRESPONSE = _descriptor.Descriptor(
  name='ExceptionResponse',
  full_name='pb.ExceptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exception_class_name', full_name='pb.ExceptionResponse.exception_class_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack_trace', full_name='pb.ExceptionResponse.stack_trace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='pb.ExceptionResponse.hostname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='pb.ExceptionResponse.port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='do_not_retry', full_name='pb.ExceptionResponse.do_not_retry', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=568,
)


_REQUESTHEADER = _descriptor.Descriptor(
  name='RequestHeader',
  full_name='pb.RequestHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_id', full_name='pb.RequestHeader.call_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trace_info', full_name='pb.RequestHeader.trace_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='pb.RequestHeader.method_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_param', full_name='pb.RequestHeader.request_param', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_block_meta', full_name='pb.RequestHeader.cell_block_meta', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='pb.RequestHeader.priority', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=743,
)


_RESPONSEHEADER = _descriptor.Descriptor(
  name='ResponseHeader',
  full_name='pb.ResponseHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_id', full_name='pb.ResponseHeader.call_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exception', full_name='pb.ResponseHeader.exception', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_block_meta', full_name='pb.ResponseHeader.cell_block_meta', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=864,
)

_CONNECTIONHEADER.fields_by_name['user_info'].message_type = _USERINFORMATION
_CONNECTIONHEADER.fields_by_name['version_info'].message_type = _VERSIONINFO
_REQUESTHEADER.fields_by_name['trace_info'].message_type = Tracing_pb2._RPCTINFO
_REQUESTHEADER.fields_by_name['cell_block_meta'].message_type = _CELLBLOCKMETA
_RESPONSEHEADER.fields_by_name['exception'].message_type = _EXCEPTIONRESPONSE
_RESPONSEHEADER.fields_by_name['cell_block_meta'].message_type = _CELLBLOCKMETA
DESCRIPTOR.message_types_by_name['UserInformation'] = _USERINFORMATION
DESCRIPTOR.message_types_by_name['VersionInfo'] = _VERSIONINFO
DESCRIPTOR.message_types_by_name['ConnectionHeader'] = _CONNECTIONHEADER
DESCRIPTOR.message_types_by_name['CellBlockMeta'] = _CELLBLOCKMETA
DESCRIPTOR.message_types_by_name['ExceptionResponse'] = _EXCEPTIONRESPONSE
DESCRIPTOR.message_types_by_name['RequestHeader'] = _REQUESTHEADER
DESCRIPTOR.message_types_by_name['ResponseHeader'] = _RESPONSEHEADER

UserInformation = _reflection.GeneratedProtocolMessageType('UserInformation', (_message.Message,), dict(
  DESCRIPTOR = _USERINFORMATION,
  __module__ = 'RPC_pb2'
  # @@protoc_insertion_point(class_scope:pb.UserInformation)
  ))
_sym_db.RegisterMessage(UserInformation)

VersionInfo = _reflection.GeneratedProtocolMessageType('VersionInfo', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONINFO,
  __module__ = 'RPC_pb2'
  # @@protoc_insertion_point(class_scope:pb.VersionInfo)
  ))
_sym_db.RegisterMessage(VersionInfo)

ConnectionHeader = _reflection.GeneratedProtocolMessageType('ConnectionHeader', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONHEADER,
  __module__ = 'RPC_pb2'
  # @@protoc_insertion_point(class_scope:pb.ConnectionHeader)
  ))
_sym_db.RegisterMessage(ConnectionHeader)

CellBlockMeta = _reflection.GeneratedProtocolMessageType('CellBlockMeta', (_message.Message,), dict(
  DESCRIPTOR = _CELLBLOCKMETA,
  __module__ = 'RPC_pb2'
  # @@protoc_insertion_point(class_scope:pb.CellBlockMeta)
  ))
_sym_db.RegisterMessage(CellBlockMeta)

ExceptionResponse = _reflection.GeneratedProtocolMessageType('ExceptionResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXCEPTIONRESPONSE,
  __module__ = 'RPC_pb2'
  # @@protoc_insertion_point(class_scope:pb.ExceptionResponse)
  ))
_sym_db.RegisterMessage(ExceptionResponse)

RequestHeader = _reflection.GeneratedProtocolMessageType('RequestHeader', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTHEADER,
  __module__ = 'RPC_pb2'
  # @@protoc_insertion_point(class_scope:pb.RequestHeader)
  ))
_sym_db.RegisterMessage(RequestHeader)

ResponseHeader = _reflection.GeneratedProtocolMessageType('ResponseHeader', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEHEADER,
  __module__ = 'RPC_pb2'
  # @@protoc_insertion_point(class_scope:pb.ResponseHeader)
  ))
_sym_db.RegisterMessage(ResponseHeader)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\tRPCProtosH\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
