# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tracing.proto

from __future__ import absolute_import, print_function

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Tracing.proto',
  package='pb',
  serialized_pb=_b('\n\rTracing.proto\x12\x02pb\"/\n\x08RPCTInfo\x12\x10\n\x08trace_id\x18\x01 \x01(\x03\x12\x11\n\tparent_id\x18\x02 \x01(\x03\x42@\n*org.apache.hadoop.hbase.protobuf.generatedB\rTracingProtosH\x01\xa0\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RPCTINFO = _descriptor.Descriptor(
  name='RPCTInfo',
  full_name='pb.RPCTInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='pb.RPCTInfo.trace_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='pb.RPCTInfo.parent_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['RPCTInfo'] = _RPCTINFO

RPCTInfo = _reflection.GeneratedProtocolMessageType('RPCTInfo', (_message.Message,), dict(
  DESCRIPTOR = _RPCTINFO,
  __module__ = 'Tracing_pb2'
  # @@protoc_insertion_point(class_scope:pb.RPCTInfo)
  ))
_sym_db.RegisterMessage(RPCTInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\rTracingProtosH\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
